export const MODIFIERS: Array<string> = [
  "hover",
  "focus",
  "focus-within",
  "focus-visible",
  "active",
  "visited",
  "target",
  "first",
  "last",
  "only",
  "odd",
  "even",
  "first-of-type",
  "last-of-type",
  "only-of-type",
  "empty",
  "disabled",
  "checked",
  "indeterminate",
  "default",
  "required",
  "valid",
  "invalid",
  "in-range",
  "out-of-range",
  "placeholder-shown",
  "autofill",
  "read-only",
  "open",
  "before",
  "after",
  "first-letter",
  "first-line",
  "marker",
  "selection",
  "file",
  "placeholder",
  // headless UI
  "ui-open",
  "ui-disabled",
  "ui-active",
  "ui-selected",
  "ui-checked",
  "ui-not-open",
  "ui-not-disabled",
  "ui-not-active",
  "ui-not-selected",
  "ui-not-checked",
];

export const BRANDING_OPTIONS_DEFAULTS = {
  _bodyFont: "Inter",
  _headingFont: "Inter",
  _roundedCorners: 5,
  _primaryColor: "#570df8",
  _secondaryColor: "#f002b8",
  _bodyBgDarkColor: "#031022",
  _bodyBgLightColor: "#fcfcfc",
  _bodyTextDarkColor: "#ffffff",
  _bodyTextLightColor: "#000000",
};
